#!/bin/bash
if [ -d "/usr/share/mural/mural" ]; then
  export PYTHONPATH="/usr/share/mural"
  exec python3 "/usr/share/mural/mural/main.py" "$@"
else
  APP="mural"
  TGT="$HOME/.local/share/$APP"
  export PYTHONPATH="$TGT"
  exec python3 "$TGT/mural/main.py" "$@"
fi
